# Generated by Django 5.0 on 2024-05-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
