# Generated by Django 5.0 on 2024-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanage', '0002_alter_employeesalary_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('num_leave_remain', models.IntegerField()),
                ('total_leave', models.IntegerField()),
            ],
        ),
    ]
