# Generated by Django 5.0 on 2024-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanage', '0003_remainleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainleave',
            name='total_leave',
            field=models.IntegerField(default=0),
        ),
    ]
