# Generated by Django 5.0 on 2024-05-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empmanage', '0004_alter_remainleave_total_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainleave',
            name='num_leave_remain',
        ),
    ]
